### ISSUE TITLE
hello world does not work ClassNotFound -Renaming? for "new Drop<HelloWorldObject>();"

### ISSUE THREAD

**Issue by nbartel** [Qabel/qabel-helloworld-module#4]
Hello,
I tried to follow the hello world. Followed the instructions I get the following Exception....
Seem that the Drop.Java class was renamed or changed in the behavior how it's called?

line 49: Drop<HelloWorldObject> drop = new Drop<HelloWorldObject>();

Cheers
Norman

See Exception/Trace:

qabel.helloworld.QblHelloWorldModule

Exception in thread "de.qabel.helloworld.QblHelloWorldModule" java.lang.NoClassDefFoundError: de/qabel/core/drop/Drop
	at de.qabel.helloworld.QblHelloWorldModule.sendMessages(QblHelloWorldModule.java:49)
	at de.qabel.helloworld.QblHelloWorldModule._run(QblHelloWorldModule.java:54)
	at de.qabel.helloworld.QblHelloWorldModule.run(QblHelloWorldModule.java:65)
Caused by: java.lang.ClassNotFoundException: de.qabel.core.drop.Drop
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 3 more
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
	at de.qabel.core.http.DropHTTP.receiveMessages(DropHTTP.java:58)
	at de.qabel.core.http.DropHTTP.receiveMessages(DropHTTP.java:48)
	at de.qabel.core.drop.DropController.retrieve(DropController.java:200)
	at de.qabel.core.drop.DropController.retrieve(DropController.java:93)
	at de.qabel.desktop.QblMain.run(QblMain.java:118)
	at de.qabel.desktop.QblMain.main(QblMain.java:39)

**Comment by aBothe** [comment]
Hi Norman, please change Drop to DropController.
The HelloWorld-code seems slightly outdated - which mainly comes because Drop shall be put on top of a new event handling system.

Anyway, if you need more sample code, please refer to qabel-core's [unittests](https://github.com/Qabel/qabel-core/blob/master/src/test/java/de/qabel/core/drop/DropControllerTest.java) :)

**Comment by nbartel** [comment]
Thanks for the fast response, will do.
